### ISSUE TITLE
Offset documentation

### ISSUE THREAD

**Issue by SleepingFox88** [SleepingFox88/BvhToMimic#1]
Issue
---

Unsure how to correctly interpret "OFFSET" properties found in .bvh files.

Questions
---

Are these local or global offsets?

![Offsets](https://i.imgur.com/HcpWefR.png)

Requests
---

Resources showing how to properly interpret .bvh file formats

**Comment by BartMoyaers** [comment]
This pdf:
[http://www.dcs.shef.ac.uk/intranet/research/public/resmes/CS0111.pdf](http://www.dcs.shef.ac.uk/intranet/research/public/resmes/CS0111.pdf)
explains a bit more about the BVH file format.

> Within the definition of each bone, the first line, delimited by the keyword OFFSET, details the translation of the origin of the bone with respect to its parent’s origin (or globally in the case of the root bone) along the x, y and z-axis respectively. 

So it seems to be a local or relative offset.

**Comment by SleepingFox88** [comment]
``translation of the origin of the bone with respect to its parent’s origin`` this is backed up by the transform positions of the bind pose when examining them in Blender. Closing issue for now.
