### ISSUE TITLE
Unrecognized contributor

### ISSUE THREAD

**Issue by SleepingFox88** [SleepingFox88/BvhToMimic#12]
# Describe the bug
Contributor BartMoyaers has made commits to master branch but is unrecognized as a contributor to this repository. Also, when looking at their commits their name is also not clickable and they have no profile picture / identicon.

# Expected behavior
- Contributors should be recognized and displayed under the /graphs/contributors page.
- Commit's contributor should have profile picture and clickable name.

# Screenshots
![](https://i.imgur.com/vDjNNUh.png)
## Normal behavior
![](https://i.imgur.com/7VlTKAM.png)
## Abnormal behavior
![](https://i.imgur.com/aixzfpS.png)

**Comment by SleepingFox88** [comment]
@BartMoyaers If you would like to be, i'd be happy to have you listed as a contributor to this repository. Otherwise I will close this issue

**Comment by BartMoyaers** [comment]
That would be great! Thanks.

**Comment by SleepingFox88** [comment]
@BartMoyaers I am not sure what is causing the issue. In my understanding, your contributions would normally already be shown. [This resource](https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile) might offer some clues. Is the email address associated with your commits, the same as the one associated with your github account? That might be the problem. You can add `.patch` to the end of one of your commit URLs to verify.

![](https://i.imgur.com/a8THHRo.png)

**Comment by BartMoyaers** [comment]
You were right, had to add my email address. Issue may be closed.

**Comment by SleepingFox88** [comment]
That fixed most things. You are now registered as a contributor and your commits have a clickable name and picture. You're not yet listed under the contributors tab (upon opening it), but that may fix on it's own with time. I am closing this issue for now.

![](https://i.imgur.com/hisrJrn.png)
![](https://i.imgur.com/pU0Ub27.png)
![](https://i.imgur.com/BHIWRaW.png)

**Comment by SleepingFox88** [comment]
You did show up on contribution graph after a while.

![](https://i.imgur.com/xZ2Ucjo.png)
