### ISSUE TITLE
Which website is the code 02_01.bvh downloaded from the code?

### ISSUE THREAD

**Issue by Tenderness0715** [SleepingFox88/BvhToMimic#18]
Hello, thank you for your contribution.
May I know which website is the code 02_01.bvh downloaded from the code?
Thank you very much.

**Comment by SleepingFox88** [comment]
I found `02_01.bvh` in [this youtube video](https://www.youtube.com/watch?v=8UaJI9E-YtM). The comments of the video provided [this download link](https://www.mediafire.com/file/o6ncxuu1oq5r6z9/cmuconvert-mb2-01-09.zip/file). The video gave a special thanks to the ` CMU Graphics Lab Motion Capture Database` which provided the data.

We may want to remove `02_01.bvh` from this repository once this program works, but for now having `02_01.bvh` in this repository makes it easy for people to start testing.

**Comment by Tenderness0715** [comment]
Thanks for response,  this is very helpful! :)

**Comment by SleepingFox88** [comment]
No problem!
