### ISSUE TITLE
Keyframe documentation

### ISSUE THREAD

**Issue by SleepingFox88** [SleepingFox88/BvhToMimic#2]
Issue
---

Unsure how to correctly interpret animation key-frame order found in .bvh files.

Questions
---

Is this data for joints from top to bottom or another order?

![AnimData](https://i.imgur.com/BLaZv9T.png)

Requests
---

Resources showing how to properly interpret .bvh file formats

**Comment by BartMoyaers** [comment]
This pdf:
[http://www.dcs.shef.ac.uk/intranet/research/public/resmes/CS0111.pdf](http://www.dcs.shef.ac.uk/intranet/research/public/resmes/CS0111.pdf)
explains a bit more about the BVH file format.

> The second line of a bone’s definition is prefixed with the keyword CHANNELS which defines the DOFs for the current bone. The importance of the order that the channels are presented is two-fold. First, the order that each channel is seen in the hierarchy section of the file exactly matches the order of the data in the motion section of the file. For example, the motion section of the file contains information for the channels of the root bone in the order defined in the hierarchy, followed by the channel data for it’s first child, followed by the channel data for that child and so on through the hierarchy. The second point to note with regards to the channel ordering is that the concatenation order of the Euler angles when creating the bone’s rotation matrix needs to follow the order depicted in the CHANNEL section. It is important to note this because the Euler order is specified for each bone, therefore it is possible to have different orders for different bones, which needs to be accounted for in order to get a correct looking animation.

So it seems to be "top to bottom", earlier defined joints come first in the data, after that all their children. (Then the next joint, with its children...)

**Comment by SleepingFox88** [comment]
@BartMoyaers Good find
