### ISSUE TITLE
Use existing BVH parser

### ISSUE THREAD

**Issue by BartMoyaers** [SleepingFox88/BvhToMimic#3]
Instead of manually creating a json file, which we then need to parse ourselves, it might be handy to use an existing parser like:
[https://github.com/20tab/bvh-python](https://github.com/20tab/bvh-python)

 (Just a proposal of course.)

I'm probably going to look into this in the future, as the BVH format seems to be used quite extensively, like in this database:
[http://mocap.cs.sfu.ca/](http://mocap.cs.sfu.ca/)

**Comment by SleepingFox88** [comment]
@BartMoyaers the existing parser you linked looks great. I'll start playing with it. Thanks for the help!

**Comment by SleepingFox88** [comment]
https://github.com/20tab/bvh-python is now being utilized.
